[package]
name = "little_rust"
version = "0.0.2"
authors = ["azusachino <azusachino@yahoo.com>"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/AzusaChino/little-rust"

[dependencies]
argh = "0.1.6"
toml = "0.5.8"
rand = "0.8.1"

[[bin]]
name = "littlt_rust"
path = "src/main.rs"

[dev-dependencies]
json = "0.12.4"

[profile.dev]
# The opt-level setting controls the number of optimizations Rust will apply to your code
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
members = [
    "minigrep"
]