[workspace]
members = ["httpie", "miniredis", "practice", "tar", "yui"]

[profile.release]
lto = true
codegen-units = 1

[profile.release.package.agent]
opt-level = 'z'
debug = false
debug-assertions = false
