[package]
name = "little_rust"
version = "0.0.2"
authors = ["azusachino <azusachino@yahoo.com>"]
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/azusachino/little-rust"

[dependencies]
anyhow = "1.0.52"
argh = "0.1.6"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.5.8"
rand = "0.8.1"
tokio = { version = "1.15.0", features = ["full"] }

[[bin]]
name = "little_rust"
path = "src/main.rs"

[dev-dependencies]
json = "0.12.4"

[profile.dev]
# The opt-level setting controls the number of optimizations Rust will apply to your code
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
members = [
    "minigrep",
    "miniredis",
    "practice",
    "scylla"
]
