[package]
name = "little_rust"
version = "0.0.1"
authors = ["azusachino <azusachino@yahoo.com>"]
edition = "2018"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/AzusaChino/little-rust"

[dependencies]
toml = "0.5.8"
json = "0.12.4"

[dev-dependencies]
