[package]
name = "wasm-web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"
wasm-bindgen = "0.2"
web-sys = "0.3"
yew = "0.19"
yew-router = "0.16"
